using System.Text;
using GenAiIncubator.LlmUtils.Core.Models;

namespace GenAiIncubator.LlmUtils.Core.Helpers;

/// <summary>
/// Helper class for exposing different customer journey classifications.
/// </summary>
public static class CustomerJourneyHelper
{
    /// <summary>
    /// Gets a distinct list of customer journey classifications.
    /// </summary>
    /// <returns>An <see cref="IEnumerable{T}"/> of distinct classification strings.</returns>
    public static IEnumerable<string> GetMainJourneys()
    {
        return GetAllCustomerJourneys().Select(_ => _.Classification).Distinct(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Gets the subcategories for a given classification.
    /// </summary>
    /// <param name="classification">The classification to filter subcategories by.</param>
    /// <returns>An <see cref="IEnumerable{T}"/> of subcategory strings.</returns>
    public static IEnumerable<string> GetSubcategories(string classification)
    {
        return GetAllCustomerJourneys().Where(_ => _.Classification.Equals(classification, StringComparison.OrdinalIgnoreCase)).Select(_ => _.Subcategory);
    }

    /// <summary>
    /// Gets a formatted string of all main journeys and their subcategories.
    /// </summary>
    /// <returns>A formatted string of main journeys and their subcategories.</returns>
    public static string GetJourneysSubcategories()
    {
        StringBuilder sb = new();
        foreach (string journey in GetMainJourneys())
        {
            sb.AppendLine(journey);
            foreach (string subcategory in GetSubcategories(journey))
                sb.AppendLine($"\t- {subcategory}");
        }
        return sb.ToString();
    }

    /// <summary>
    /// Gets a list of customer journey classifications.
    /// </summary>
    /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="CustomerJourneyClassification"/> objects.</returns>
    public static IEnumerable<CustomerJourneyClassification> GetAllCustomerJourneys()
    {
        return
        [
            new CustomerJourneyClassification(111199, "Aanvullende producten en diensten", "Opwekkers"),
            new CustomerJourneyClassification(111198, "Aanvullende producten en diensten", "Samen in Zon"),
            new CustomerJourneyClassification(111114, "Aanvullende producten en diensten", "Duurzaam wonen check"),
            new CustomerJourneyClassification(111108, "Aanvullende producten en diensten", "Zonnepanelen / Zonhuur"),
            new CustomerJourneyClassification(111109, "Aanvullende producten en diensten", "Slimme thermostaat"),
            new CustomerJourneyClassification(111116, "Aanvullende producten en diensten", "Exclusief"),
            new CustomerJourneyClassification(111174, "Aanvullende producten en diensten", "E-mobility"),
            new CustomerJourneyClassification(112114, "Algemene vragen", "Duurzaam wonen check"),
            new CustomerJourneyClassification(112189, "Algemene vragen", "Energie App inloggen"),
            new CustomerJourneyClassification(112192, "Algemene vragen", "Ongeoorloofde klantbenadering"),
            new CustomerJourneyClassification(112177, "Algemene vragen", "Vraag type meter / aansluiting"),
            new CustomerJourneyClassification(112112, "Algemene vragen", "Tarievencommunicatie"),
            new CustomerJourneyClassification(112113, "Algemene vragen", "Informatie verduurzamen"),
            new CustomerJourneyClassification(112175, "Algemene vragen", "Mijn Vattenfall inloggen"),
            new CustomerJourneyClassification(112178, "Algemene vragen", "Storing"),
            new CustomerJourneyClassification(112179, "Algemene vragen", "Retourpost"),
            new CustomerJourneyClassification(112180, "Algemene vragen", "Technische vraag "),
            new CustomerJourneyClassification(112201, "Algemene vragen", "Phishing"),
            new CustomerJourneyClassification(112204, "Algemene vragen", "Prijsplafond"),
            new CustomerJourneyClassification(106194, "Betaalprobleem", "Vraag Budgetbeheer/Bewindvoering"),
            new CustomerJourneyClassification(106195, "Betaalprobleem", "Vraag MSNP / WIJN"),
            new CustomerJourneyClassification(106196, "Betaalprobleem", "Vraag Verlicht"),
            new CustomerJourneyClassification(106197, "Betaalprobleem", "Vraag WSNP / Faillissementen"),
            new CustomerJourneyClassification(106110, "Betaalprobleem", "Afmelden nav faillissement"),
            new CustomerJourneyClassification(106155, "Betaalprobleem", "Vraag schuldhulp algemeen"),
            new CustomerJourneyClassification(106115, "Betaalprobleem", "Storno (mislukte auto incasso)"),
            new CustomerJourneyClassification(106148, "Betaalprobleem", "Aanmaning"),
            new CustomerJourneyClassification(106149, "Betaalprobleem", "Aanvraag uitstel betaling"),
            new CustomerJourneyClassification(106150, "Betaalprobleem", "Aanvraag betalingsregeling"),
            new CustomerJourneyClassification(106151, "Betaalprobleem", "Status betalingsregeling"),
            new CustomerJourneyClassification(106152, "Betaalprobleem", "Vraag incasso"),
            new CustomerJourneyClassification(106153, "Betaalprobleem", "Vraag verrekening"),
            new CustomerJourneyClassification(106154, "Betaalprobleem", "Voorkomen einde levering"),
            new CustomerJourneyClassification(106161, "Betaalprobleem", "Uithuizen"),
            new CustomerJourneyClassification(106999, "Betaalprobleem", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(106202, "Betaalprobleem", "Aanmelding Fin. Hulpverlening"),
            new CustomerJourneyClassification(106203, "Betaalprobleem", "Afmelding Fin. Hulpverlening"),
            new CustomerJourneyClassification(105999, "Betalen", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(105115, "Betalen", "Storno (mislukte auto incasso)"),
            new CustomerJourneyClassification(105143, "Betalen", "Openstaand saldo"),
            new CustomerJourneyClassification(105144, "Betalen", "Status betaling"),
            new CustomerJourneyClassification(105145, "Betalen", "Betalingsherinnering"),
            new CustomerJourneyClassification(105146, "Betalen", "Mislukken betaling"),
            new CustomerJourneyClassification(105147, "Betalen", "Status terugbetaling"),
            new CustomerJourneyClassification(107103, "Energiecontract vernieuwen", "Termijnbedrag aanpassen"),
            new CustomerJourneyClassification(107114, "Energiecontract vernieuwen", "Duurzaam wonen check"),
            new CustomerJourneyClassification(107164, "Energiecontract vernieuwen", "Multi-sites aanmelding"),
            new CustomerJourneyClassification(107157, "Energiecontract vernieuwen", "Persoonlijk advies"),
            new CustomerJourneyClassification(107104, "Energiecontract vernieuwen", "Info (huidige) contract"),
            new CustomerJourneyClassification(107111, "Energiecontract vernieuwen", "Blijven Loont"),
            new CustomerJourneyClassification(107123, "Energiecontract vernieuwen", "Annuleren contract"),
            new CustomerJourneyClassification(107124, "Energiecontract vernieuwen", "Correctie gegevens contract"),
            new CustomerJourneyClassification(107126, "Energiecontract vernieuwen", "Aanmelden/ Contract aanvragen"),
            new CustomerJourneyClassification(107127, "Energiecontract vernieuwen", "Informatie tarieven"),
            new CustomerJourneyClassification(107156, "Energiecontract vernieuwen", "Informatie korting"),
            new CustomerJourneyClassification(107158, "Energiecontract vernieuwen", "Status nieuwe contract"),
            new CustomerJourneyClassification(107176, "Energiecontract vernieuwen", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(107999, "Energiecontract vernieuwen", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(104112, "Jaarafrekening", "Tarievencommunicatie"),
            new CustomerJourneyClassification(104999, "Jaarafrekening", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(104103, "Jaarafrekening", "Termijnbedrag aanpassen"),
            new CustomerJourneyClassification(104114, "Jaarafrekening", "Duurzaam wonen check"),
            new CustomerJourneyClassification(104168, "Jaarafrekening", "Termijnbedragadvies of seintje"),
            new CustomerJourneyClassification(104111, "Jaarafrekening", "Blijven Loont"),
            new CustomerJourneyClassification(104118, "Jaarafrekening", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(104120, "Jaarafrekening", "Correctie / check meterstanden"),
            new CustomerJourneyClassification(104125, "Jaarafrekening", "Vraag Welkomstpremie/ geschenk"),
            new CustomerJourneyClassification(104137, "Jaarafrekening", "Datum jaarafrekening"),
            new CustomerJourneyClassification(104138, "Jaarafrekening", "Jaarafrekening niet ontvangen"),
            new CustomerJourneyClassification(104139, "Jaarafrekening", "Begrijpen jaarafrekening"),
            new CustomerJourneyClassification(104140, "Jaarafrekening", "Uitleg hoge jaarafrekening"),
            new CustomerJourneyClassification(104141, "Jaarafrekening", "Uitleg belastingen (zakelijk)"),
            new CustomerJourneyClassification(104142, "Jaarafrekening", "Vraag salderen / terugleveren"),
            new CustomerJourneyClassification(104153, "Jaarafrekening", "Vraag verrekening"),
            new CustomerJourneyClassification(104156, "jaarafrekening", "Informatie korting"),
            new CustomerJourneyClassification(104170, "Jaarafrekening", "Bespaaradvies"),
            new CustomerJourneyClassification(104171, "Jaarafrekening", "Energiescan"),
            new CustomerJourneyClassification(104176, "Jaarafrekening", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(101114, "klant worden", "Duurzaam wonen check"),
            new CustomerJourneyClassification(101121, "Klant worden", "Waarborgsom"),
            new CustomerJourneyClassification(101164, "klant worden", "Multi-sites aanmelding"),
            new CustomerJourneyClassification(101168, "klant worden", "Termijnbedragadvies of seintje"),
            new CustomerJourneyClassification(101157, "Klant worden", "Persoonlijk advies"),
            new CustomerJourneyClassification(101101, "Klant worden", "Overstapkorting aanvragen"),
            new CustomerJourneyClassification(101102, "Klant worden", "Onterechte afmelding"),
            new CustomerJourneyClassification(101104, "klant worden", "Info (huidige) contract"),
            new CustomerJourneyClassification(101111, "Klant worden", "Blijven Loont"),
            new CustomerJourneyClassification(101113, "klant worden", "Informatie verduurzamen"),
            new CustomerJourneyClassification(101117, "Klant worden", "Overstapkorting info"),
            new CustomerJourneyClassification(101118, "Klant worden", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(101119, "Klant worden", "Slimme meterstanden"),
            new CustomerJourneyClassification(101120, "Klant worden", "Correctie / check meterstanden"),
            new CustomerJourneyClassification(101122, "Klant worden", "Status Overstap"),
            new CustomerJourneyClassification(101123, "Klant worden", "Annuleren contract"),
            new CustomerJourneyClassification(101124, "Klant worden", "Correctie gegevens contract"),
            new CustomerJourneyClassification(101125, "Klant worden", "Vraag Welkomstpremie/ geschenk"),
            new CustomerJourneyClassification(101126, "Klant worden", "Aanmelden/ Contract aanvragen"),
            new CustomerJourneyClassification(101127, "Klant worden", "Informatie tarieven"),
            new CustomerJourneyClassification(101128, "Klant worden", "Onterechte aanmelding"),
            new CustomerJourneyClassification(101156, "Klant worden", "Informatie korting"),
            new CustomerJourneyClassification(101176, "Klant worden", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(101181, "Klant worden", "D2D ervaring"),
            new CustomerJourneyClassification(101999, "Klant worden", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(113200, "Nabestaanden", "Afhandeling Erfenis"),
            new CustomerJourneyClassification(113179, "Nabestaanden", "Retourpost"),
            new CustomerJourneyClassification(113118, "Nabestaanden", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(113165, "Nabestaanden", "Afmelden nav overlijden"),
            new CustomerJourneyClassification(113182, "Nabestaanden", "Melding overlijden (Erven van)"),
            new CustomerJourneyClassification(113183, "Nabestaanden", "Naamswijziging ivm overlijden"),
            new CustomerJourneyClassification(999999, "niet gespecificeerde journey", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(999103, "niet gespecificeerde journey", "Termijnbedrag aanpassen"),
            new CustomerJourneyClassification(999114, "niet gespecificeerde journey", "Duurzaam wonen check"),
            new CustomerJourneyClassification(999121, "niet gespecificeerde journey", "Waarborgsom"),
            new CustomerJourneyClassification(999164, "niet gespecificeerde journey", "Multi-sites aanmelding"),
            new CustomerJourneyClassification(999168, "niet gespecificeerde journey", "Termijnbedragadvies of seintje"),
            new CustomerJourneyClassification(999101, "niet gespecificeerde journey", "Overstapkorting aanvragen"),
            new CustomerJourneyClassification(999102, "niet gespecificeerde journey", "Onterechte afmelding"),
            new CustomerJourneyClassification(999104, "niet gespecificeerde journey", "Info (huidige) contract"),
            new CustomerJourneyClassification(999110, "niet gespecificeerde journey", "Afmelden nav faillissement"),
            new CustomerJourneyClassification(999111, "niet gespecificeerde journey", "Blijven Loont"),
            new CustomerJourneyClassification(999113, "niet gespecificeerde journey", "Informatie verduurzamen"),
            new CustomerJourneyClassification(999115, "niet gespecificeerde journey", "Storno (mislukte auto incasso)"),
            new CustomerJourneyClassification(999117, "niet gespecificeerde journey", "Overstapkorting info"),
            new CustomerJourneyClassification(999118, "niet gespecificeerde journey", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(999119, "niet gespecificeerde journey", "Slimme meterstanden"),
            new CustomerJourneyClassification(999120, "niet gespecificeerde journey", "Correctie / check meterstanden"),
            new CustomerJourneyClassification(999122, "niet gespecificeerde journey", "Status Overstap"),
            new CustomerJourneyClassification(999123, "niet gespecificeerde journey", "Annuleren contract"),
            new CustomerJourneyClassification(999124, "niet gespecificeerde journey", "Correctie gegevens contract"),
            new CustomerJourneyClassification(999125, "niet gespecificeerde journey", "Vraag Welkomstpremie/ geschenk"),
            new CustomerJourneyClassification(999126, "niet gespecificeerde journey", "Aanmelden/ Contract aanvragen"),
            new CustomerJourneyClassification(999146, "niet gespecificeerde journey", "Mislukken betaling"),
            new CustomerJourneyClassification(999148, "niet gespecificeerde journey", "Aanmaning"),
            new CustomerJourneyClassification(999149, "niet gespecificeerde journey", "Aanvraag uitstel betaling"),
            new CustomerJourneyClassification(999150, "niet gespecificeerde journey", "Aanvraag betalingsregeling"),
            new CustomerJourneyClassification(999152, "niet gespecificeerde journey", "Vraag incasso"),
            new CustomerJourneyClassification(999127, "niet gespecificeerde journey", "Informatie tarieven"),
            new CustomerJourneyClassification(999128, "niet gespecificeerde journey", "Onterechte aanmelding"),
            new CustomerJourneyClassification(999157, "niet gespecificeerde journey", "Persoonlijk advies"),
            new CustomerJourneyClassification(999142, "niet gespecificeerde journey", "Vraag salderen / terugleveren"),
            new CustomerJourneyClassification(999153, "niet gespecificeerde journey", "Vraag verrekening"),
            new CustomerJourneyClassification(999156, "niet gespecificeerde journey", "Informatie korting"),
            new CustomerJourneyClassification(999163, "niet gespecificeerde journey", "Begrijpen Eindnota"),
            new CustomerJourneyClassification(999167, "niet gespecificeerde journey", "Uitleg hoge eindnota"),
            new CustomerJourneyClassification(999170, "niet gespecificeerde journey", "Bespaaradvies"),
            new CustomerJourneyClassification(999171, "niet gespecificeerde journey", "Energiescan"),
            new CustomerJourneyClassification(999176, "niet gespecificeerde journey", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(109190, "Opzeggen", "Eindnota niet ontvangen"),
            new CustomerJourneyClassification(109107, "Opzeggen", "Annuleren opzegging (Behoud)"),
            new CustomerJourneyClassification(109110, "Opzeggen", "Afmelden nav faillissement"),
            new CustomerJourneyClassification(109102, "Opzeggen", "Onterechte afmelding"),
            new CustomerJourneyClassification(109105, "Opzeggen", "Opzeggen contract / status opzeggen"),
            new CustomerJourneyClassification(109106, "Opzeggen", "Opzegvergoeding"),
            new CustomerJourneyClassification(109111, "opzeggen", "Blijven Loont"),
            new CustomerJourneyClassification(109120, "Opzeggen", "Correctie / check meterstanden"),
            new CustomerJourneyClassification(109123, "Opzeggen", "Annuleren contract"),
            new CustomerJourneyClassification(109163, "Opzeggen", "Begrijpen Eindnota"),
            new CustomerJourneyClassification(109166, "Opzeggen", "Retentie offer/winback"),
            new CustomerJourneyClassification(109167, "Opzeggen", "Uitleg hoge eindnota"),
            new CustomerJourneyClassification(109999, "Opzeggen", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(102191, "Personaliseer gegevens", "Naamswijziging"),
            new CustomerJourneyClassification(102132, "Personaliseer gegevens", "Status wijziging gegevens"),
            new CustomerJourneyClassification(102119, "Personaliseer gegevens", "Slimme meterstanden"),
            new CustomerJourneyClassification(102129, "Personaliseer gegevens", "Wijzigen persoonlijke gegevens"),
            new CustomerJourneyClassification(102130, "Personaliseer gegevens", "Wijzigen betaalgegevens"),
            new CustomerJourneyClassification(102131, "Personaliseer gegevens", "Wijzigen voorkeuren"),
            new CustomerJourneyClassification(102134, "Personaliseer gegevens", "Zakelijk afwijkende facturatie"),
            new CustomerJourneyClassification(102176, "Personaliseer gegevens", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(102999, "Personaliseer gegevens", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(102133, "Personaliseer gegevens", "Kan niet wijzigen in Mijn Vattenfall"),
            new CustomerJourneyClassification(103103, "Termijnfactuur", "Termijnbedrag aanpassen"),
            new CustomerJourneyClassification(103168, "Termijnfactuur", "Termijnbedragadvies of seintje"),
            new CustomerJourneyClassification(103118, "Termijnfactuur", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(103135, "Termijnfactuur", "Kopie termijnfactuur versturen (zakelijk)"),
            new CustomerJourneyClassification(103136, "Termijnfactuur", "Begrijpen termijnbedrag/factuur"),
            new CustomerJourneyClassification(103176, "Termijnfactuur", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(103999, "Termijnfactuur", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(110999, "Verbruik", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(110103, "Verbruik", "Termijnbedrag aanpassen"),
            new CustomerJourneyClassification(110114, "Verbruik", "Duurzaam wonen check"),
            new CustomerJourneyClassification(110168, "Verbruik", "Termijnbedragadvies of seintje"),
            new CustomerJourneyClassification(110188, "Verbruik", "Verbruikscorrectie"),
            new CustomerJourneyClassification(110193, "Verbruik", "Correctie defecte meter"),
            new CustomerJourneyClassification(110118, "Verbruik", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(110119, "Verbruik", "Slimme meterstanden"),
            new CustomerJourneyClassification(110142, "Verbruik", "Vraag salderen / terugleveren"),
            new CustomerJourneyClassification(110169, "Verbruik", "Mijn Verbruik (web/app)"),
            new CustomerJourneyClassification(110170, "Verbruik", "Bespaaradvies"),
            new CustomerJourneyClassification(110171, "Verbruik", "Energiescan"),
            new CustomerJourneyClassification(110172, "Verbruik", "Technisch adviseur"),
            new CustomerJourneyClassification(110173, "Verbruik", "Energierapport"),
            new CustomerJourneyClassification(110176, "Verbruik", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(108103, "Verhuizen", "Termijnbedrag aanpassen"),
            new CustomerJourneyClassification(108164, "Verhuizen", "Multi-sites aanmelding"),
            new CustomerJourneyClassification(108167, "Verhuizen", "Uitleg hoge eindnota"),
            new CustomerJourneyClassification(108185, "Verhuizen", "Verhuizing annuleren of aanpassen datum"),
            new CustomerJourneyClassification(108186, "Verhuizen", "Vragen over Online verhuizing "),
            new CustomerJourneyClassification(108187, "Verhuizen", "Status verhuizing "),
            new CustomerJourneyClassification(108104, "Verhuizen", "Info (huidige) contract"),
            new CustomerJourneyClassification(108114, "Verhuizen", "Duurzaam wonen check"),
            new CustomerJourneyClassification(108121, "Verhuizen", "Waarborgsom"),
            new CustomerJourneyClassification(108122, "Verhuizen", "Status Overstap"),
            new CustomerJourneyClassification(108124, "Verhuizen", "Correctie gegevens contract"),
            new CustomerJourneyClassification(108125, "Verhuizen", "Vraag Welkomstpremie/ geschenk"),
            new CustomerJourneyClassification(108126, "Verhuizen", "Aanmelden/ Contract aanvragen"),
            new CustomerJourneyClassification(108168, "Verhuizen", "Termijnbedragadvies of seintje"),
            new CustomerJourneyClassification(108171, "Verhuizen", "Energiescan"),
            new CustomerJourneyClassification(108176, "verhuizen", "Mijn Vattenfall overig"),
            new CustomerJourneyClassification(108101, "Verhuizen", "Overstapkorting aanvragen"),
            new CustomerJourneyClassification(108102, "Verhuizen", "Onterechte afmelding"),
            new CustomerJourneyClassification(108111, "Verhuizen", "Blijven Loont"),
            new CustomerJourneyClassification(108117, "Verhuizen", "Overstapkorting info"),
            new CustomerJourneyClassification(108118, "Verhuizen", "(hulp) bij doorgeven meterstanden"),
            new CustomerJourneyClassification(108120, "Verhuizen", "Correctie / check meterstanden"),
            new CustomerJourneyClassification(108127, "Verhuizen", "Informatie tarieven"),
            new CustomerJourneyClassification(108128, "Verhuizen", "Onterechte aanmelding"),
            new CustomerJourneyClassification(108159, "Verhuizen", "Uitleg bij verhuizen"),
            new CustomerJourneyClassification(108160, "Verhuizen", "Volledige verhuizing"),
            new CustomerJourneyClassification(108161, "Verhuizen", "Uithuizen"),
            new CustomerJourneyClassification(108162, "Verhuizen", "Inhuizen"),
            new CustomerJourneyClassification(108163, "Verhuizen", "Begrijpen Eindnota"),
            new CustomerJourneyClassification(108170, "Verhuizen", "Bespaaradvies"),
            new CustomerJourneyClassification(108999, "Verhuizen", "niet gespecificeerd topic"),
            new CustomerJourneyClassification(110205, "Verbruik", "Postcoderoos"),
            new CustomerJourneyClassification(101206, "Klant worden", "Voordeelladen"),
            new CustomerJourneyClassification(102206, "Personaliseer gegevens", "Voordeelladen"),
            new CustomerJourneyClassification(103206, "Termijnfactuur", "Voordeelladen"),
            new CustomerJourneyClassification(104206, "Jaarafrekening", "Voordeelladen"),
            new CustomerJourneyClassification(105206, "Betalen", "Voordeelladen"),
            new CustomerJourneyClassification(106206, "Betaalprobleem", "Voordeelladen"),
            new CustomerJourneyClassification(108206, "Verhuizen", "Voordeelladen"),
            new CustomerJourneyClassification(109206, "Opzeggen", "Voordeelladen"),
            new CustomerJourneyClassification(110206, "Verbruik", "Voordeelladen"),
            new CustomerJourneyClassification(112206, "Algemene vragen", "Voordeelladen"),
            new CustomerJourneyClassification(999206, "niet gespecificeerde journey", "Voordeelladen"),
            new CustomerJourneyClassification(101207, "Klant worden", "Dynamische prijs"),
            new CustomerJourneyClassification(102207, "Personaliseer gegevens", "Dynamische prijs"),
            new CustomerJourneyClassification(103207, "Termijnfactuur", "Dynamische prijs"),
            new CustomerJourneyClassification(104207, "Jaarafrekening", "Dynamische prijs"),
            new CustomerJourneyClassification(105207, "Betalen", "Dynamische prijs"),
            new CustomerJourneyClassification(106207, "Betaalprobleem", "Dynamische prijs"),
            new CustomerJourneyClassification(108207, "Verhuizen", "Dynamische prijs"),
            new CustomerJourneyClassification(109207, "Opzeggen", "Dynamische prijs"),
            new CustomerJourneyClassification(110207, "Verbruik", "Dynamische prijs"),
            new CustomerJourneyClassification(112207, "Algemene vragen", "Dynamische prijs"),
            new CustomerJourneyClassification(999207, "niet gespecificeerde journey", "Dynamische prijs"),
        ];
    }
}