parameters:
  - name: subscription
    type: string
    values:
    - 'Connection TO CEP DEV/TST'
    - 'Connection TO CEP ACC/PRD'

  - name: environmentDtap
    type: string

  - name: projectName
    type: string

  - name: bicepFileName
    type: string
    default: main.bicep

  - name: resourceGroup
    type: string

  - name: appServicePlan
    type: string

  - name: keyVaultName
    type: string

  - name: whatifDeployment
    type: string

  - name: infraFolderRelativePath
    type: string

  - name: functionAppName
    type: string


steps:
- checkout: self
  displayName: 'Checkout Code'

- task: AzureCLI@2    
  displayName: "Provision Azure resources"
  inputs:
    azureSubscription: ${{ parameters.subscription }}
    scriptType: "pscore"
    scriptLocation: "inlineScript"
    inlineScript: |
      param($whatifDeployment)

      $infraFolderPath = "$(System.DefaultWorkingDirectory)/${{ parameters.infraFolderRelativePath }}"
      cd $infraFolderPath

      $deployName = "${{parameters.projectName}}-$(Build.BuildNumber)"
      
      if ($whatifDeployment -eq 'true') {
        az deployment group what-if `
          --name "$deployName" `
          --resource-group "${{parameters.resourceGroup}}" `
          --template-file "${{parameters.bicepFileName}}" `
          --parameters `
            environmentDtap="${{parameters.environmentDtap}}" `
            appServicePlanName="${{parameters.appServicePlan}}" `
            keyVaultName="${{parameters.keyVaultName}}" `
            functionAppName="${{parameters.functionAppName}}" `
          --mode "Incremental" `
          --result-format "FullResourcePayloads"
      } 
      else {
        az deployment group create `
          --name "$deployName" `
          --resource-group "${{parameters.resourceGroup}}" `
          --template-file "${{parameters.bicepFileName}}" `
          --parameters `
            environmentDtap="${{parameters.environmentDtap}}" `
            appServicePlanName="${{parameters.appServicePlan}}" `
            keyVaultName="${{parameters.keyVaultName}}" `
            functionAppName="${{parameters.functionAppName}}" `
          --mode "Incremental"
      }
    arguments: '-whatifDeployment ${{parameters.whatifDeployment}}'
